# Generated by Django 4.2.6 on 2023-10-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.BigIntegerField()),
                ('dateofbirth', models.DateField()),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
